### 📄 `templates/nodepool.yaml`
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.node_group_name }}-np
spec:
  template:
    metadata:
      labels:
        deployment.group: {{ .Values.node_group_name }}
        nodepool: {{ .Values.node_group_name }}
    spec:
      nodeClassRef:
        name: {{ .Values.node_group_name }}-ec2
        kind: EC2NodeClass
        group: karpenter.k8s.aws
      requirements:
        {{- range .Values.requirements }}
        - key: {{ .key }}
          operator: {{ .operator }}
          values:
            {{- range .values }}
            - {{ . | quote }}
            {{- end }}
        {{- end }}
      {{- if or .Values.gpu.enabled .Values.taints.enabled }}
      taints:
        {{- if .Values.gpu.enabled }}
        - key: nvidia.com/gpu
          value: "dedicated"
          effect: NoSchedule
        {{- end }}
        {{- range .Values.taints.enabled | default list }}
        - key: {{ .key | quote }}
          {{- if .value }}
          value: {{ .value | quote }}
          {{- end }}
          effect: {{ .effect | quote }}
        {{- end }}
      {{- end }}
      expireAfter: {{ .Values.expireAfter | default "Never" }}
  limits:
    cpu: {{ .Values.limits.cpu | quote }}
    memory: {{ .Values.limits.memory | quote }}
  disruption:
    consolidationPolicy: {{ .Values.consolidationPolicy | default "WhenEmptyOrUnderutilized" }}
    consolidateAfter: {{ .Values.consolidateAfter | default "300s" }}
    {{- if .Values.budgets }}
    budgets:
      {{- range .Values.budgets }}
      - nodes: {{ .nodes | quote }}
        schedule: {{ .schedule | quote }}
        duration: {{ .duration | quote }}
      {{- end }}
    {{- end }}