{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stateless.configMapName" . }}
  labels:
    {{- include "stateless.labels" . | nindent 4 }}
{{- with .Values.configMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.configMap.binaryData }}
binaryData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
