name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm charts
        run: |
          mkdir -p .cr-release-packages
          for chart in charts/*; do
            helm dependency update "$chart" || true
            helm package "$chart" --destination .cr-release-packages
          done

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Move packaged charts to gh-pages
        run: |
          mkdir -p gh-pages
          cp -r .cr-release-packages/*.tgz gh-pages/

      - name: Regenerate Helm repo index
        run: |
          cd gh-pages
          helm repo index . --url https://nailabx.github.io/naix-charts

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update Helm chart packages and index" || echo "No changes to commit"
          git push origin gh-pages