name: Publish Helm Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Build and publish Helm charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create gh-pages worktree
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git worktree add gh-pages gh-pages

      - name: Package Helm charts
        run: |
          mkdir -p gh-pages
          helm package stateless --destination gh-pages
          helm package stateful --destination gh-pages
          helm package nodepool --destination gh-pages
          helm repo index gh-pages --url https://nailabx.github.io/naix-charts/

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git add .
          git commit -m "Update Helm chart packages and index"
          git push origin HEAD:gh-pages